# Generated by Django 4.0.3 on 2022-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('implicit', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('explicits', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('item_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('api_id', models.IntegerField(default=1)),
                ('item_slot', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ascendancy', models.CharField(choices=[('Slayer', 'https://poe.ninja/images/classes/Slayer_avatar.png'), ('Gladiator', 'https://poe.ninja/images/classes/Gladiator_avatar.png')], default='Slayer', max_length=100)),
                ('right_hand', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('left_hand', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('helm', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('chest', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('gloves', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('boots', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('belt', models.CharField(blank=True, default='/static/imgs/smallplus.png', max_length=255)),
                ('amulet', models.CharField(blank=True, default='/static/imgs/smallplus.png', max_length=255)),
                ('ring1', models.CharField(blank=True, default='/static/imgs/smallplus.png', max_length=255)),
                ('ring2', models.CharField(blank=True, default='/static/imgs/smallplus.png', max_length=255)),
                ('items', models.ManyToManyField(to='main_app.item')),
            ],
        ),
    ]
