# Generated by Django 4.0.3 on 2022-03-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ascendancy', models.CharField(blank=True, default=None, max_length=255)),
                ('right_hand', models.CharField(blank=True, default=None, max_length=255)),
                ('left_hand', models.CharField(blank=True, default=None, max_length=255)),
                ('helm', models.CharField(blank=True, default=None, max_length=255)),
                ('chest', models.CharField(blank=True, default=None, max_length=255)),
                ('gloves', models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255)),
                ('boots', models.CharField(blank=True, default=None, max_length=255)),
                ('belt', models.CharField(blank=True, default=None, max_length=255)),
                ('amulet', models.CharField(blank=True, default=None, max_length=255)),
                ('ring1', models.CharField(blank=True, default=None, max_length=255)),
                ('ring2', models.CharField(blank=True, default='/static/imgs/smallplus.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('implicit', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('explicits', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('item_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('api_id', models.IntegerField(default=1)),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
