# Generated by Django 4.0.3 on 2022-03-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='amulet',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='ascendancy',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='belt',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='boots',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='chest',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='gloves',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='helm',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='left_hand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='right_hand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='ring1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='ring2',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
