# Generated by Django 4.0.3 on 2022-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
