# Generated by Django 4.0.3 on 2022-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_character_ascendancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ascendancy',
            field=models.CharField(choices=[('https://poe.ninja/images/classes/Slayer_avatar.png', 'Slayer'), ('https://poe.ninja/images/classes/Gladiator_avatar.png', 'Gladiator')], default='Slayer', max_length=100),
        ),
    ]
