# Generated by Django 4.0.3 on 2022-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_character_amulet_alter_character_ring1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chest',
            field=models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='helm',
            field=models.CharField(blank=True, default='/static/imgs/plus.png', max_length=255),
        ),
    ]
