# Generated by Django 4.0.3 on 2022-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_character_amulet_alter_character_ascendancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='api_id',
            field=models.IntegerField(default=1),
        ),
    ]
