# Generated by Django 4.0.3 on 2022-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='api_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
