# Generated by Django 4.0.3 on 2022-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_item_api_id_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='api_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
