# Generated by Django 4.0.3 on 2022-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_item_api_id_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='explicits',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='implicit',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
