# Generated by Django 4.0.3 on 2022-03-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_item_explicits_alter_item_implicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='explicits',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='implicit',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
